-- App icon mapping using Nerd Font icons
local app_icons = {
  ["Arc"] = "",
  ["Firefox"] = "",
  ["Safari"] = "",
  ["Chrome"] = "",
  ["Chromium"] = "",
  ["Brave Browser"] = "",
  ["Code"] = "󰨞",
  ["Code - Insiders"] = "󰨞",
  ["VSCode"] = "󰨞",
  ["VSCodium"] = "󰨞",
  ["Wezterm"] = "",
  ["Terminal"] = "",
  ["iTerm2"] = "",
  ["Alacritty"] = "",
  ["Kitty"] = "",
  ["Slack"] = "󰒱",
  ["Discord"] = "󰙯",
  ["Spotify"] = "",
  ["Music"] = "",
  ["Messages"] = "󰍡",
  ["Telegram"] = "󰍡",
  ["Signal"] = "󰍡",
  ["Mail"] = "",
  ["Thunderbird"] = "",
  ["Calendar"] = "",
  ["Notes"] = "",
  ["Notion"] = "",
  ["Finder"] = "",
  ["Preview"] = "",
  ["System Settings"] = "",
  ["System Preferences"] = "",
  ["Docker"] = "",
  ["Docker Desktop"] = "",
  ["Obsidian"] = "󱓷",
  ["Vim"] = "",
  ["Neovim"] = "",
  ["MacVim"] = "",
  ["Emacs"] = "",
  ["Zed"] = "󰈺",
  ["IntelliJ IDEA"] = "",
  ["PyCharm"] = "",
  ["WebStorm"] = "",
  ["Postman"] = "",
  ["Figma"] = "",
  ["Zoom.us"] = "󰊫",
  ["zoom.us"] = "󰊫",
  ["Microsoft Teams"] = "󰊫",
}

return {
  get_app_icon = function(app_name)
    return app_icons[app_name] or ""
  end
}
